### ISSUE TITLE
Get and Set freeze function

### ISSUE THREAD

**Issue by BenJamesAndo** [amosyuen/ha-epson-projector-link#160]
**Is your feature request related to a problem? Please describe.**
I'd like to easily be able to freeze and unfreeze a projector's image. This comes in handy when you want an image to remain on the screen but need to disconnect or restart the source device.

**Describe the solution you'd like**
Set Freeze to on or off and Get the freeze status

**Describe alternatives you've considered**
I've tried via Send Command but there's a few issues. One, when I send `FREEZE ON` the projector status updates to OFF. Interestingly this doesn't occur with `FREEZE OFF` or if the projector is already frozen and `FREEZE ON` is sent. If I create a script to set `FREEZE ON`, wait 10ms then set `PWR?` it shows up as the projector being on again. However the Send Command doesn't output the response so there's no easy way to verify if it was successful within Home Assistant.

**Additional context**
For now I'm using the below configuration.yaml to make it work, but it involves polling it outside of this integration.
```
  - platform: telnet
    switches:
      epson_east_projector_freeze:
        resource: 192.168.20.12
        port: 3629
        command_on: "\x45\x53\x43\x2F\x56\x50\x2E\x6E\x65\x74\x10\x03\x00\x00\x00\x00\x46\x52\x45\x45\x5a\x45\x20\x4f\x4e\x0d"
        command_off: "\x45\x53\x43\x2F\x56\x50\x2E\x6E\x65\x74\x10\x03\x00\x00\x00\x00\x46\x52\x45\x45\x5a\x45\x20\x4f\x46\x46\x0d"
        command_state: "\x45\x53\x43\x2F\x56\x50\x2E\x6E\x65\x74\x10\x03\x00\x00\x00\x00\x46\x52\x45\x45\x5a\x45\x3f\x0d"
        value_template: "{{ 'ON' in value }}"

```

I could open a separate issue to track down the reason why sending `FREEZE ON` causes it to think that the projector is off if you like.
This is the response directly from my projector
`FREEZE ON:IMEVENT=0017 0001:FREEZE OFF:IMEVENT=0017 0000:`
